[chat]
azure_deployment = "gpt-4"  # ou "gpt-35-turbo"
azure_api_key = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
azure_endpoint = "https://ton-instance.openai.azure.com/"
azure_api_version = "2023-12-01-preview"

[embedding]
azure_deployment = "text-embedding-ada-002"  # ✅ modèle valide
azure_api_key = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
azure_endpoint = "https://ton-instance.openai.azure.com/"
azure_api_version = "2023-12-01-preview"
