[chat]
azure_deployment = "fake-chat-deployment"
azure_api_key = "sk-fake-api-key-1234567890"
azure_endpoint = "https://fake-endpoint.openai.azure.com/"
azure_api_version = "2023-12-01-preview"

[embedding]
azure_deployment = "fake-embedding-deployment"
azure_api_key = "sk-fake-embedding-key-0987654321"
azure_endpoint = "https://fake-endpoint.openai.azure.com/"
azure_api_version = "2023-12-01-preview"
