[chat]
azure_deployment = "gpt-chat"
azure_api_key = "F26eGKv1zA6wFMc2rRe3TNNK3ecGvFKU9OU9syutZTtSBfMrM9hXJQQJ99BFACHYHv6XJ3w3AAAAACOG3tmS"
azure_endpoint = "https://projet-rag-openai.openai.azure.com/"
azure_api_version = "2023-12-01-preview"

[embedding]
azure_deployment = "embed-ada"
azure_api_key = "F26eGKv1zA6wFMc2rRe3TNNK3ecGvFKU9OU9syutZTtSBfMrM9hXJQQJ99BFACHYHv6XJ3w3AAAAACOG3tmS"
azure_endpoint = "https://projet-rag-openai.openai.azure.com/"
azure_api_version = "2023-12-01-preview"
