embedding:
  azure_endpoint: "__ENV:AZURE_EMBED_ENDPOINT"
  azure_deployment: "__ENV:AZURE_EMBED_DEPLOY"
  azure_api_version: "2023-05-15"
  azure_api_key: "__ENV:AZURE_EMBED_KEY"

chat:
  azure_endpoint: "__ENV:AZURE_CHAT_ENDPOINT"
  azure_deployment: "__ENV:AZURE_CHAT_DEPLOY"
  azure_api_version: "2023-05-15"
  azure_api_key: "__ENV:AZURE_CHAT_KEY"
