embedding:
  azure_endpoint: "https://mon-instance-openai-france.openai.azure.com"
  azure_deployment: "text-embedding-ada-002"
  azure_api_version: "2024-02-15"
  azure_api_key: "sk-abc1234567890abcdef1234567890xyz"

chat:
  azure_endpoint: "https://mon-instance-openai-france.openai.azure.com"
  azure_deployment: "gpt-35-turbo"
  azure_api_version: "2024-02-15"
  azure_api_key: "sk-def9876543210fedcba9876543210uvw"
