[theme]
primaryColor = "#4B8BBE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true

[client]
showSidebarNavigation = true

[layout]
wide = false

[general]
pageTitle = "Assistant Documentaire RAG"
