[chat]
azure_deployment = "gpt-chat"
azure_api_key = "sk-..."
azure_endpoint = "https://TON_ENDPOINT.openai.azure.com/"
azure_api_version = "2023-12-01-preview"

[embedding]
azure_deployment = "gpt-embedding"
azure_api_key = "sk-..."
azure_endpoint = "https://TON_ENDPOINT.openai.azure.com/"
azure_api_version = "2023-12-01-preview"
