[embedding]
azure_endpoint = "https://xxx.openai.azure.com/"
azure_deployment = "embedding-model"
azure_api_key = "YOUR_AZURE_API_KEY"
azure_api_version = "2023-12-01-preview"

[chat]
azure_endpoint = "https://xxx.openai.azure.com/"
azure_deployment = "chat-model"
azure_api_key = "YOUR_AZURE_API_KEY"
azure_api_version = "2023-12-01-preview"
